language: java
jdk: oraclejdk8

# default Travis install script with accessExternalSchema added to the end
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Djavax.xml.accessExternalSchema=all

script:
  - mvn test --batch-mode -Djavax.xml.accessExternalSchema=all
  - mvn checkstyle:check --batch-mode --fail-never
